backup:
 dobackup:             # hacer backup (Yes/No)
 path:                 # camino a los archivos para backup (string)
 
reducir:
 doreducir :           # hacer la reduccion (Yes/No)
 imobj:                # lista de imagenes de ciencia (string)
 path:                 # camino a imobj,imflat,imbias,imdark (string)
 imflat:               # lista de imagenes flat (string)
 imbias:               # lista de imagenes bias (string)
 opciones:
  dark: No             # hacer correccion por dark (Yes/No)
  imdark:              # lista de imagenes dark (string)
  
fotometria:
 dofotometria:         # hacer fotometria (Yes/No)
 imobj:                # imagenes para hacer fotometria (string)
 path:                 # camino a imobj (string)
 opciones:
   buscarest:          # buscar estrellas automaticamente (Yes/No)
   autofwhm:           # buscar fwhm automaticamente (Yes/No)
   telescope:          # telescopio usado (HSH o JS)
   RF:                 # si se uso un reductor focal (Yes/No)
   autocielo:          # buscar desv estandar del cielo automaticante (Yes/No)
   tr:                 # treshold       (entero)
   annulus:            # annulus radio  (entero)
   dannulus:           # dannulus radio (entero)
   apertura:           # radios de apertura (string en formato iraf)
  
tabla:
 dotabla:              # generar tabla (Yes/No)
 phouts:               # tabla o tablas para formatear (string) 
 path:                 # camino a phots (string) 
 opciones:
  formato:             # formato de tablas (string, formatos de astropy.Tables)
  esquema:             # esquema de tablas (imagen,estrella)
