backup:
  dobackup: false
  opciones:
    filename: null
    formato: tar
  path: null
fotometria:
  dofotometria: false
  imobj: Robj.in
  opciones:
    annulus: 30.0
    apertura: 0.0
    autoapertura: true
    autocielo: true
    autofwhm: true
    buscarest: true
    cielo: 0.0
    coords: None
    dannulus: 5.0
    fwhm: 0.0
    pathc: None
    tr: 4.0
  path: /home/natalia/Documentos/Materias/Sistemas/DatosCASLEO/Sistemas19/data/20190906/CCD_Directo
reducir:
  doreducir: false
  imbias: None
  imflat: null
  imobj: None
  limflat: None
  opciones:
    dark: false
    filterfield: null
    imdark: None
    pathdk: None
  overscan: null
  pathbi: None
  pathf: None
  pathfl: null
  pathim: None
  trim: null
tabla:
  dotabla: true
  opciones:
    esquema: imagen
    formato: html
  path: /home/natalia/Documentos/Materias/Sistemas/DatosCASLEO/Sistemas19/data/20190906/CCD_Directo
  phouts: Robj_phots.in
