

backup:                # hacer backup
 dobackup: No
 path: '/home/guevaran/20180601'
 
reducir:
 imobj: 'images.in'                # lista de imagenes de ciencia
 doreducir : No       # hacer la reduccion
 path: '/home/guevaran/20180601'
 imflat: 'flats.in'              # lista de imagenes flat
 imbias: 'bias.in'              # lista de imagenes bias
 opciones :
  dark: No             # correccion por dark
  imdark:              # lista de imagenes dark
  
fotometria:
 imobj: 'imphot.in'                #
 dofotometria: No      # hacer fotometria
 path: '/home/guevaran/20180601'
 opciones:
   buscarest: Yes      # buscar estrellas
   autofwhm: Yes       # buscar fwhm
   telescope: JS         # HSH o JS
   RF: No              # si se uso un reductor focal
   autocielo: Yes      # buscar desv estandar del cielo
   tr: 5                # treshold
   annulus: 30
   dannulus: 5
   apertura: range(1,31)
  
tabla:
 dotabla: Yes          # generar tabla
 path: '/home/guevaran/20180601'
 phouts: 'imphot.in.phot'
 opciones:
  formato:
  apertura: range(1,31)

