backup:
  dobackup: true
  opciones:
    filename: null
    formato: zip
  path: null
fotometria:
  dofotometria: false
  imobj: null
  opciones:
    RF: false
    annulus: 0.0
    apertura: 0.0
    autoapertura: true
    autocielo: true
    autofwhm: true
    buscarest: true
    cielo: 0.0
    coords: null
    dannulus: 0.0
    fwhm: 0.0
    pathc: null
    telescopio: JS
    tr: 0.0
  path: null
reducir:
  doreducir: false
  imbias: null
  imflat: null
  imobj: null
  opciones:
    dark: false
    filterfield: null
    imdark: null
    pathdk: null
  pathbi: null
  pathfl: null
  pathim: null
tabla:
  dotabla: true
  opciones:
    esquema: imagen
    formato: fixed_width
  path: /home/natalia/20180601
  phouts: imphot_phots.in
