

backup:                # hacer backup
 dobackup: Yes
 path: '/home/natalia/20180601'
 
reducir:
 imobj: 'images.in'                # lista de imagenes de ciencia
 doreducir : Yes       # hacer la reduccion
 path: '/home/natalia/20180601'
 imflat: 'flats.in'              # lista de imagenes flat
 imbias: 'bias.in'              # lista de imagenes bias
 opciones :
  dark: No             # correccion por dark
  imdark:              # lista de imagenes dark
  
fotometria:
 imobj: 'imphot.in'                #imagenes
 dofotometria: Yes      # hacer fotometria
 path: '/home/natalia/20180601'
 opciones:
   buscarest: Yes      # buscar estrellas
   autofwhm: Yes       # buscar fwhm
   telescope: JS         # HSH o JS
   RF: No              # si se uso un reductor focal
   autocielo: Yes      # buscar desv estandar del cielo
   tr: 5                # treshold
   annulus: 30
   dannulus: 5
   apertura: "2:5:1"
  
tabla:
 dotabla: Yes          # generar tabla
 path: '/home/natalia/20180601'
 phouts: 'imphot_phots.in'
 opciones:
  formato:                         # formato de tablas
  esquema:                         # esquema de tablas