backup:
  dobackup: true
  opciones:
    filename: ''
    formato: zip
  path: ''
fotometria:
  dofotometria: false
  imobj: ''
  opciones:
    RF: false
    annulus: 0.0
    apertura: 0.0
    autoapertura: true
    autocielo: true
    autofwhm: true
    buscarest: true
    cielo: 0.0
    coords: ''
    dannulus: 0.0
    fwhm: 0.0
    pathc: ''
    telescopio: JS
    tr: 0.0
  path: ''
reducir:
  doreducir: false
  imbias: ''
  imflat: ''
  imobj: ''
  opciones:
    dark: false
    filterfield: ''
    imdark: ''
    pathdk: ''
  pathbi: ''
  pathfl: ''
  pathim: ''
tabla:
  dotabla: false
  opciones:
    esquema: imagen
    formato: aastex
  path: ''
  phouts: ''
