backup:
  dobackup: true
  opciones:
    filename: null
    formato: tar
  path: null
fotometria:
  dofotometria: false
  imobj: None
  opciones:
    RF: false
    annulus: 30.0
    apertura: 0.0
    autoapertura: true
    autocielo: true
    autofwhm: true
    buscarest: true
    cielo: 0.0
    coords: None
    dannulus: 5.0
    fwhm: 0.0
    pathc: None
    telescopio: JS
    tr: 4.0
  path: None
reducir:
  doreducir: false
  imbias: None
  imflat: null
  imobj: None
  limflat: None
  opciones:
    dark: false
    filterfield: null
    imdark: None
    pathdk: None
  overscan: null
  pathbi: None
  pathf: None
  pathfl: null
  pathim: None
  trim: null
tabla:
  dotabla: false
  opciones:
    esquema: estrella
    formato: latex
  path: None
  phouts: None
