

backup:                # hacer backup
 dobackup: Yes
 dirname:
 path:
 bformat:              

reducir:
 imobj:                # lista de imagenes de ciencia
 doreducir : Yes       # hacer la reduccion
 path:
 imflat:               # lista de imagenes flat
 imbias:               # lista de imagenes bias
 opciones :
  dark: No             # correccion por dark
  imdark:              # lista de imagenes dark
  
fotometria:
 imobj:                #
 dofotometria: Yes     # hacer fotometria
 path:
 opciones:
   buscarest: Yes      # buscar estrellas
   autofwhm: Yes       # buscar fwhm
   telescope:          # HSH o JS
   RF: No              # si se uso un reductor focal
   autocielo: Yes      # buscar desv estandar del cielo
   tr:                 # treshold
   annulus:
   dannulus:
   apertura:
  
tabla:
 dotabla: Yes          # generar tabla
 path:
 phouts:
 opciones:
  formato:
  apertura:

