backup:
  dobackup: true
  opciones:
    filename: null
    formato: tar
  path: /home/natalia/20180601
fotometria:
  dofotometria: false
  imobj: imphot.in
  opciones:
    RF: false
    annulus: 30.0
    apertura: 0.0
    autoapertura: true
    autocielo: true
    autofwhm: true
    buscarest: true
    cielo: 0.0
    coords: null
    dannulus: 5.0
    fwhm: 0.0
    pathc: null
    telescopio: JS
    tr: 4.0
  path: /home/natalia/20180601
reducir:
  doreducir: true
  imbias: bias.in
  imflat: flats.in
  imobj: images.in
  opciones:
    dark: false
    filterfield: null
    imdark: null
    pathdk: null
  overscan: '[1:409, 410:410]'
  pathbi: /home/natalia/20180601
  pathfl: /home/natalia/20180601
  pathim: /home/natalia/20180601
  trim: '[10:400,10:400]'
tabla:
  dotabla: false
  opciones:
    esquema: estrella
    formato: aastex
  path: /home/natalia/20180601
  phouts: imphot_phots.in
